name: Database CI

on:
  push:
    branches:
      - main
    paths:
      - "supabase/**"
  pull_request:
    paths:
      - "supabase/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 2.26.9

      - name: Start Supabase local development setup
        run: supabase start

      - name: Run database tests
        run: supabase test db

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Verify generated types are valid
        run: |
          # Generate fresh types
          supabase gen types typescript --local > lib/database.types.ts
          
          # Run TypeScript compiler to check for type errors
          echo "Checking TypeScript compilation..."
          if bunx tsc --noEmit --skipLibCheck; then
            echo "✅ Generated types are valid"
          else
            echo "❌ Generated types have compilation errors"
            exit 1
          fi